### ISSUE TITLE
Providers pending to migrate the new provider class way

### ISSUE THREAD

**Issue by barrientosvctor** [koikiss-dev/jimov_api#166]
## Anime
- [ ] 9Anime (pending to migrate to TypeScript) #153 
- [ ] AnimeBlix (pending to merge) #164 
- [ ] Animeflv
- [ ] AnimeLatinoHD (pending to merge) #164 
- [ ] Animevostfr (pending to merge) #164
- [ ] Gogoanime
- [ ] Monoschinos
- [ ] OtakuTV (pending to migrate to TypeScript) #154 
- [ ] TioAnime
- [ ] Wcostream (pending to merge) #164
- [ ] Zoro

## Manga
- [ ] MangaBuddy
- [ ] MangaReader
- [ ] Comick (pending to merge) #164
- [ ] Inmanga (pending to merge) #164
- [ ] Manganelo
- [ ] Nhentai
- [ ] Tmomanga (pending to migrate to TypeScript) #155
